---
- hosts: webserver1
  gather_facts: no
  vars_files:
   - hellow.yml
  tasks:
   - name: check the connectiviry
     shell: cat "{{ filename }}" | grep "{{ username }}"
     register: a
   - name: get the variable value
     debug:
      var: a.stdout
